/**
 * 圣遗物主词条表
 */ 
export const ArtifactParamTypes = [
    'Crit Rate',
    'Crit DMG',
    'Attack power',
    'Elemantal Mastery',
    'Energy Recharge',
    'HP',
    'Deff',
    'Physical Damage Bonus',
    'Healing Bonus',
    'Geo Damage Bonus',
    'Anemo  Damage Bonus',
    'Cryo  Damage Bonus',
    'Hydro Damage Bonus',
    'Pyro Damage Bonus',
    'Electro Damage Bonus',
]
/**
 * 圣遗物副词条表
 */
export const ArtifactSubParamTypes = [
    'Crit rate',
    'Critical damage',
    'Attack',
    'Element masterpico',
    'Element Replenishment Efficiency',
    'life value',
    'Defense',
    'Physical damage bonus',
    'Treatment bonus',
]
/**
 * Holy relics name
 */
export const ArtifactNames = [
    '磐陀裂生之花',
    '嵯峨群峰之翼',
    '星罗圭璧之晷',
    '巉岩琢塑之樽',
    '不动玄石之相',
    '历经风雪的思念',
    '摧冰而行的执望',
    '冰雪故园的终期',
    '遍结寒霜的傲骨',
    '破冰踏雪的回音',
    '染血的铁之心',
    '染血的黑之羽',
    '骑士染血之时',
    '染血骑士之杯',
    '染血的铁假面',
    '魔女的炎之花',
    '魔女常燃之羽',
    '魔女破灭之时',
    '魔女的心之火',
    '焦灼的魔女帽',
    '角斗士的留恋',
    '角斗士的归宿',
    '角斗士的希冀',
    '角斗士的酣醉',
    '角斗士的凯旋',
    '饰金胸花',
    '追忆之风',
    '坚铜罗盘',
    '沉波之盏',
    '酒渍船帽',
    '渡火者的决绝',
    '渡火者的解脱',
    '渡火者的煎熬',
    '渡火者的醒悟',
    '渡火者的智慧',
    '远方的少女之心',
    '少女飘摇的思念',
    '少女苦短的良辰',
    '少女片刻的闲暇',
    '少女易逝的芳颜',
    '宗室之花',
    '宗室之翎',
    '宗室时计',
    '宗室银瓮',
    '宗室面具',
    '夏祭之花',
    '夏祭终末',
    '夏祭之刻',
    '夏祭水玉',
    '夏祭之面',
    '平雷之心',
    '平雷之羽',
    '平雷之刻',
    '平雷之器',
    '平雷之冠',
    '雷鸟的怜悯',
    '雷灾的孑遗',
    '雷霆的时计',
    '降雷的凶兆',
    '唤雷的头冠',
    '野花记忆的绿野',
    '猎人青翠的箭羽',
    '翠绿猎人的笃定',
    '翠绿猎人的容器',
    '翠绿的猎人之冠',
    '乐团的晨光',
    '琴师的箭羽',
    '终幕的时计',
    '吟游者之壶',
    '指挥的礼帽',
    '战狂的蔷薇',
    '战狂的翎羽',
    '战狂的时计',
    '战狂的骨杯',
    '战狂的鬼面',
    '勇士的勋章',
    '勇士的期许',
    '勇士的坚毅',
    '勇士的壮行',
    '勇士的冠冕',
    '守护之花',
    '守护徽印',
    '守护座钟',
    '守护之皿',
    '守护束带',
    '流放者之花',
    '流放者之羽',
    '流放者怀表',
    '流放者之杯',
    '流放者头冠',
    '赌徒的胸花',
    '赌徒的羽饰',
    '赌徒的怀表',
    '赌徒的骰盅',
    '赌徒的耳环',
    '教官的胸花',
    '教官的羽饰',
    '教官的怀表',
    '教官的茶杯',
    '教官的帽子',
    '武人的红花',
    '武人的羽饰',
    '武人的水漏',
    '武人的酒杯',
    '武人的头巾',
    '祭水礼冠',
    '祭火礼冠',
    '祭雷礼冠',
    '祭冰礼冠',
    '故人之心',
    '归乡之羽',
    '逐光之石',
    '异国之盏',
    '感别之冠',
    '学士的书签',
    '学士的羽笔',
    '学士的时钟',
    '学士的墨杯',
    '学士的镜片',
    '奇迹之花',
    '奇迹之羽',
    '奇迹之沙',
    '奇迹之杯',
    '奇迹耳坠',
    '冒险家之花',
    '冒险家尾羽',
    '冒险家怀表',
    '冒险家金杯',
    '冒险家头带',
    '幸运儿绿花',
    '幸运儿鹰羽',
    '幸运儿沙漏',
    '幸运儿之杯',
    '幸运儿银冠',
    '游医的银莲',
    '游医的枭羽',
    '游医的怀钟',
    '游医的药壶',
    '游医的方巾',
    '勋绩之花',
    '昭武翎羽',
    '金铜时晷',
    '盟誓金爵',
    '将帅兜鍪',
    '无垢之花',
    '贤医之羽',
    '停摆之刻',
    '超越之盏',
    '嗤笑之面',
    'Flower of Life',
    'Plume of Death',
    'Sands of Eon',
    'Goblet of Eonothem',
    'Circlet of Logos',
    'Archaic Petra',
    'Flower of Creviced Cliff',
    'Feather of Jagged Peaks',
    'Sundial of Enduring Jade',
    'Goblet of Chiseled Crag',
    'Stainless Bloom',
    'Mask of Solitude Basalt',
    'Icebreaker',
    'Snowswept Memory',
    'Icebreaker s Resolve',
    'Frozen Homelands Demise',
    'Frost-Weaved Dignity',
    'Broken Rime s Echo',
    'Bloodstained Chivalry',
    'Bloodstained Flower of Iron',
    'Bloodstained Black Plume',
    'Bloodstained Final Hour',
    'Bloodstained Chevalier s Goblet',
    'Bloodstained Iron Mask',
    'Crimson Witch of Flames',
    'Witch s Flower of Blaze',
    'Witch s Ever-Burning Plume',
    'Witch s End Time',
    'Witch s Heart Flames',
    'Witch s Scorching Hat',
    'Gladiator s Finale',
    'Gladiator s Nostalgia',
    'Gladiator s Destiny',
    'Gladiator s Longing',
    'Gladiator s Intoxication',
    'Gladiator s Triumphus',
    'Heart of Depth',
    'Gilded Corsage',
    'Gust of Nostalgia',
    'Copper Compass',
    'Goblet of Thundering Deep',
    'Wine-Stained Tricorne',
    'Lavawalker',
    'Lavawalker s Resolution',
    'Lavawalker s Salvation',
    'Lavawalker s Torment',
    'Lavawalker s Epiphany',
    'Lavawalker sWisdom',
    'Maiden Beloved',
    'Maiden sDistant Love',
    'Maiden s Heart-stricken Infatuation',
    'Maiden sPassing Youth',
    'Maiden sFleeting Leisure',
    'Maiden sFading Beauty',
    'Noblesse Oblige',
    'Royal Flora',
    'Royal Plume',
    'Royal Pocket Watch',
    'Royal Silver Urn',
    'Royal Masque',
    'Pale Flame',
    'Stainless Bloom',
    'Wise Doctor sPinion',
    'Moment of Cessation',
    'Surpassing Cup',
    'Mocking Mask',
    'Retracing Bolide',
    'Summer Night sBloom',
    'Summer Night sFinale',
    'Summer Night sMoment',
    'Summer Night sWaterballoon',
    'Summer Night sMask',
    'Tenacity of the Millelith',
    'Flower of Accolades',
    'Ceremonial War-Plume',
    'Orichalceous Time-Dial',
    'Noble sPledging Vessel',
    'General sAncient Helm',
    'Thundering Fury',
    'Thunderbird sMercy',
    'Survivor of Catastrophe',
    'Hourglass of Thunder',
    'Omen of Thunderstorm',
    'Thunder Summoner sCrown',
    'Thundersoother',
    'Thundersoother sHeart',
    'Thundersoother sPlume',
    'Hour of Soothing Thunder',
    'Thundersoother sGoblet',
    'Thundersoother sDiadem',
    'Viridescent Venerer',
    'In Remembrance of Viridescent Fields',
    'Viridescent Arrow Feather',
    'Viridescent Venerer sDetermination',
    'Viridescent Venerer sVessel',
    'Viridescent Venerer sDiadem',
    'Wanderer sTroupe',
    'Troupe sDawnlight',
    'Bard sArrow Feather',
    'Concert sFinal Hour',
    'Wanderer sString Kettle',
    'Conductor sTop Hat',

]
/**
 *  Equiped Hero Arifact
 */
export const ArtifactUsers = [
    '空已装备',
    '荧已装备',
    '安柏已装备',
    '凯亚已装备',
    '丽莎已装备',
    '琴已装备',
    '可莉已装备',
    '诺艾尔已装备',
    '芭芭拉已装备',
    '温迪已装备',
    '雷泽已装备',
    '迪卢克已装备',
    '班尼特已装备',
    '菲谢尔已装备',
    '北斗已装备',
    '凝光已装备',
    '香菱已装备',
    '行秋已装备',
    '重云已装备',
    '砂糖已装备',
    '莫娜已装备',
    '刻晴已装备',
    '七七已装备',
    '达达利亚已装备',
    '迪奥娜已装备',
    '钟离已装备',
    '辛焱已装备',
    '阿贝多已装备',
    '甘雨已装备',
    '魈已装备',
    '胡桃已装备',
    '罗莎莉亚已装备',
]
